runners:
 AWS-runner:
  #image: public.ecr.aws/y2s4f3y9/ubuntu-generic #
  image: ubuntu
  
jobs:   
 hello-world:
  resource_spec: micro
  runner: AWS-runner  
  current_working_directory: ~/
  output:
   artifact:
    - h* 
  steps:
   - run:
      name: Text Hello World
      command: echo "Hello World" > hello.txt

 hello-world-2:
  resource_spec: micro
  runner: AWS-runner
  depends:
   - hello-world
  input:
   artifact:
    - hello-world
  current_working_directory: ~/
  steps:
   - run:
      name: Say Hello World
      command: echo "Hello World"       
      
workflows:
 hello-world-workflow:
  triggers:
   - manual 

  jobs:
   - hello-world
   - hello-world-2
